### PR TITLE
Intern dependencies

### PR DESCRIPTION
**Pull request by cquiroz**
Dependencies are a bit problematic on giapi-glue-cc so this PR interns them into our source tree. The reasons are:

* Ensure that we have the correct version numbers
* Add instructions on how to build each dependency on a way compatible with `giapi-glue-cc`
* Some dependencies don't compile cleanly on CentOS 7, these versions do compile

Note that all dependencies are either Apache or MIT-licensed

### CODE REVIEW

**Comment by arturog8m** [comment]
Looks good to me. I think you will need to update the README file as it still says it was built with RHEL 5, back in 2008. But that's a different PR.  👍

**Comment by arturog8m** [comment]
Actually - since you have changed the way the library is going to be built, the top level README file should  be updated as part of this PR.

**Comment by cquiroz** [comment]
iAs a general comment, we have a rhel5.5 branch too, in case we need to update GPI

**Comment by cquiroz** [comment]
Readme was updated as requested

**Review by swalker2m — APPROVED** [review]
Makes sense. 👍

**Pull request merged**
